sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"

before_script:
  - npm install -g gulp
script: gulp default

install:
  - npm install

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - demo-version